apiVersion: v1
data:
  nginx.conf: |+
    server {
      listen 80 ;
      listen [::]:80 ;
      
      server_name *.nwapi.srrain.kro.kr 1.1.17.18;
      charset utf-8;
      client_max_body_size 128M;

      real_ip_header proxy_protocol;
      set_real_ip_from    0.0.0.0/0;

      location / {

        proxy_set_header X-Real-IP       $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header Host            $host;
        proxy_pass http://django:8000;

      }

      location /static/ {
        alias /app/static/;
      }

      location = /50x.html {
        root   /usr/share/nginx/html;
      } 

      if ($http_x_forwarded_proto = 'http') {
        return 301 https://$host$request_uri;
      }
    }
kind: ConfigMap
metadata:
  name: {{ include "nginx-django.fullname" . }}-conf
