{{- if .Values.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mongodb.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "mongodb.serviceAccountName" . }}
{{- end }}
