{{- if .Values.dockersecret.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: #요건 삭제좀~ 키 변경했음...ㅜ
kind: Secret
metadata:
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  name: {{ .Values.dockersecret.name }}
type: kubernetes.io/dockerconfigjson
{{- end }}
