apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gateway
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.19.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true