
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.19.0-beta.1
    helm:
       
      releaseName: istio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true



      #  values: 
      #    profile: default
      #    components:
      #      pilot:
      #        enabled: true
      #      istiod:
      #        enabled: true
      #      egressGateways:
      #      - name: default
      #        enabled: true
