apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: base
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.19.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true