apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springcloud
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://gitlab.srrain.kro.kr/root/sample-spring-microservices-kubernete-helm.git
    targetRevision: HEAD
    path: templates
  
  destination:
    server: https://kubernetes.default.svc
    namespace: springcloud
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true
