kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 23.4.0
    helm:
      parameters: {}
      releaseName: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

      #  values: |
      #    prometheus:
      #      replicas: 1
      #      service:
      #        type: ClusterIP
      #        ports:
      #        - name: web
      #          port: 9090
      #      alerting:
      #        receiver:
      #        - name: email
      #          email:
      #            to: ['admin@example.com']
      #            bcc: ['dev@example.com']
      #    prometheusRules:
      #      - name: istio-rules
      #        rules:
      #        - alert: IstioPilotNotReady
      #          expr: up{job="istio-pilot"} == 0
      #          for: 1m
      #          labels:
      #            alertname: IstioPilotNotReady
      #            severity: critical
