apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: charts/notification
    targetRevision: {{ .Values.spec.source.targetRevision }}
  
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: appofapps
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true