{{- if .Values.dockersecret.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: #asd
kind: Secret
metadata:
  labels:
    {{- include "hcxapi.labels" . | nindent 4 }}
  name: {{ .Values.dockersecret.name }}
type: kubernetes.io/dockerconfigjson
{{- end }}

